format:
  html: {toc: true, toc-depth: 4, theme: spacelab}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: LLaMPPL.clj
  chapters: [index.qmd, setup.qmd, llamppl.utils.qmd, llamppl.llm.qmd, llamppl.cache.qmd, llamppl.trie.qmd, llamppl.smc.qmd]
